export const SYMPTOMS: string[] = [
  'Fatigue',
  'Headache',
  'Chest Pain',
  'Shortness of Breath',
  'Nausea',
  'Dizziness',
  'Fever',
  'Cough',
  'Sore Throat',
  'Body Aches',
  'Chills',
  'Congestion',
  'Loss of Appetite',
  'Insomnia',
  'Anxiety',
  'Palpitations',
  'Swelling',
  'Blurred Vision',
];
